services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://url-shortner:postgres@db:5432/url-shortner"
      HOST: http://localhost:3000

  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: url-shortner
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortner
