services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://url-shortener:postgres@db:5432/url-shortener"
      HOST: http://localhost:3000

  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: url-shortener
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener
